// <auto-generated />
using ApiFuturo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiFuturo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211014011428_AddModel")]
    partial class AddModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiFuturo.Models.Pronostico", b =>
                {
                    b.Property<string>("FuturId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LinkImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Palabras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuturId");

                    b.ToTable("Futuros");
                });
#pragma warning restore 612, 618
        }
    }
}
